### ISSUE TITLE
New ciphers

### ISSUE THREAD

**Issue by asterriya** [loyess/Shell#101]
Check that https://github.com/XTLS/Xray-core/releases/tag/v1.5.6 and it's very important to add new ciphers.

**Comment by loyess** [comment]
ss-rust 对于新加密方式还只是预发布版本，而且 ss-windows 和 ss-android 客户端也没有跟进，等各个平台都有了稳定版本了再说，暂时不考虑。

**Comment by loyess** [comment]
```
curl -OL https://github.com/loyess/2022/raw/main/2022script.sh
chmod +x 2022script.sh
./2022script.sh
```
