### ISSUE TITLE
错误 - 语法错误 | Bug - Syntex error

### ISSUE THREAD

**Issue by jeffshead** [loyess/Shell#105]
```
[root@vps ~]# ./ss-plugins.sh
./ss-plugins.sh：第 1564 行：意外标记“换行符”附近的语法错误
./ss-plugins.sh：第 1564 行：`esacpt_update'
```
怎么修？

```
[root@vps ~]# ./ss-plugins.sh
./ss-plugins.sh: line 1564: syntax error near unexpected token `newline'
./ss-plugins.sh: line 1564: `esacpt_update'
```
How to fix?

**Comment by loyess** [comment]
我也不知道该怎么修复，虽然报错给出了行号，然而根据行号无法定位到哪出错了。还有更多信息吗？

**Comment by jeffshead** [comment]
我跑了`wget -N --no-check-certificate -c -t3 -T60 -O ss-plugins.sh https://git.io/fjlbl`。 **ss-plugins.sh** 文件必须已损坏。 看起来原始文件没有被完全覆盖。 我再次运行 `wget -N --no-check-certificate -c -t3 -T60 -O ss-plugins.sh https://git.io/fjlbl` 并修复了 **ss-plugins.sh 中的代码 **。 因此，原始报告的问题已解决。

但是，我运行该命令的原因是我试图执行更新，因为 SSL 证书已过期并且没有自动更新。 运行 `./ss-plugins.sh update` 没有帮助。 我如何卸载 Caddy 2，因为运行 `./ss-plugins.sh uninstall` 不会删除 Caddy。

----------------------

I ran `wget -N --no-check-certificate -c -t3 -T60 -O ss-plugins.sh https://git.io/fjlbl`. The **ss-plugins.sh** file must have become corrupted. It looks like the original file wasn't completely overwritten. I ran `wget -N --no-check-certificate -c -t3 -T60 -O ss-plugins.sh https://git.io/fjlbl` again and it fixed the code in **ss-plugins.sh**. So the original reported issue is solved.

However, the reason why I ran that command was because I was trying to perform an update because the SSL cert expired and did not auto-update. Running `./ss-plugins.sh update` did not help. How do I uninstall Caddy 2 since running `./ss-plugins.sh uninstall` does not remove Caddy.

**Comment by loyess** [comment]
无法删除 caddy 是 修复 #95 #97 时 没做前向兼容导致的，执行以下命令 可以删除 caddy。
```
# CentOS
chkconfig --del caddy

# Debian/Ubuntu
update-rc.d -f caddy remove


rm -rf /usr/local/caddy
rm -rf /etc/init.d/caddy
rm -rf /usr/bin/caddy
```
或者
```
touch /root/.WebInstallMark
./ss-plugins.sh uninstall
```
