### ISSUE TITLE
部分ubuntu 18.04未初始安装curl会导致出错

### ISSUE THREAD

**Issue by cqjerry** [loyess/Shell#11]
./ss-plugins.sh: line 205: curl: command not found
./ss-plugins.sh: line 205: curl: command not found
./ss-plugins.sh: line 1133: show_config: command not found

**Comment by loyess** [comment]
有的系统可能没有安装curl命令，手动安装下吧！

apt -y install curl

**Comment by cqjerry** [comment]
谢谢。
我只是想帮助你把一键脚本调整得更完整点。

**Comment by loyess** [comment]
谢谢！

你在使用哪一个模式的情况下，有出现caddy启动不了的状况？

**Comment by cqjerry** [comment]
1、v2ray
2、ws+tls+web

**Comment by loyess** [comment]
之前的有一个版本，是caddy安装不了，我修复过了，我在测试时，并没有碰到caddy启动不了的状况，你现在还有碰到么？或者你如果在出现这种状况，可以来反馈下

**Comment by cqjerry** [comment]
刚升级到最新版，还是会有这种情况。
方便加TG吗，可以贴图直观些。
@cqjerry 
谢谢！

**Comment by loyess** [comment]
没在用tg 这里也可以贴图

**Comment by cqjerry** [comment]
镜像站点的网址格式我是使用默认的，
其他要填写的参数也是按照提示写的。

/etc/shadowsocks-libev/config.json里关于plugin_opts那段需要把fullchain.pem和privkey.pem写进去吗？

**Comment by cqjerry** [comment]
![Snipaste_2019-10-15_15-44-14](https://user-images.githubusercontent.com/7488975/66810911-c015d300-ef62-11e9-9d2b-f605bb01c884.png)

**Comment by loyess** [comment]
我都是使用的是init.d里面的启动文件，不是systemctl命令的。

你用/etc/init.d/caddy restart  重启caddy

然后看看caddy的日志
cat /tmp/caddy.log

**Comment by cqjerry** [comment]
root@LA:~# /etc/init.d/caddy restart
caddy is stopped
Starting caddy success
root@LA:~# cat /tmp/caddy.log
Activating privacy features... done.
2019/10/15 08:33:03 Listen: listen tcp :443: bind: address already in use
Activating privacy features... done.
2019/10/15 09:04:01 Listen: listen tcp :443: bind: address already in use

**Comment by loyess** [comment]
你的443端口已经在使用，caddy要用443端口启动

**Comment by cqjerry** [comment]
呵呵，被ss占用了
![Snipaste_2019-10-15_16-14-01](https://user-images.githubusercontent.com/7488975/66813171-e0479100-ef66-11e9-9c98-a3c4e31c2a78.png)

**Comment by loyess** [comment]
端口填写后的地方有注释，选择插件v2ray-plugin的4和5选项，以及选择插件cloak时，ss的端口都不能是443

**Comment by cqjerry** [comment]
嗯嗯，我的语文是体育老师教的，没有看到“以及”两个字，我就误解了。
![Snipaste_2019-10-15_16-17-10](https://user-images.githubusercontent.com/7488975/66813817-0e79a080-ef68-11e9-8f91-fda476c50b47.png)

**Comment by loyess** [comment]
问题解决了就行。

**Comment by cqjerry** [comment]
多谢你的耐心解答。
期待看到你的更加完善，更加强大的作品。

**Comment by loyess** [comment]
我添加了端口检测，输入的端口被占用时，会提示你重新输入！如果你选择的插件是Cloak或者V2ray-plugin插件的4或5选项，即使你SS端口输入的是443，也会根据判断，将你的SS给重置为可用的非443端口。

**Comment by cqjerry** [comment]
那是否可以通过手工修改caddy的json文件，把443端口让给ss用呢？

**Comment by loyess** [comment]
那就和脚本无关了，那是用户行为，我没法阻止你这么做，即使它会导致错误。
