### ISSUE TITLE
Shadowsocks+V2ray+Nginx+域名伪装 出现问题

### ISSUE THREAD

**Issue by Agandrew** [loyess/Shell#112]
Shadowsocks+V2ray+Nginx+域名伪装 出现问题，安装完以后Nginx启动不了，显示以下错误：

Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.

**Comment by tunlong** [comment]
systemctl status nginx.service 看一眼什么报错呢
