### ISSUE TITLE
v2ray-plugin ws+tls+web+cdn 按步骤安装后 出现已安装未启动的情况

### ISSUE THREAD

**Issue by MurrddoL** [loyess/Shell#12]
root@xxx:~# ./ss-plugins.sh
 Shadowsocks-libev一键管理脚本 [v2.2.5 Online]

    1. BBR
    2. Install
    3. Uninstall
     
 当前状态: 已安装 但 未启动
使用 ./ss-plugins.sh start 后
Shadowsocks-libev (pid 27592) is already running.
Starting v2ray-plugin success
Starting caddy success

但再次使用./ss-plugins.sh后
还是显示 当前状态: 已安装 但 未启动

**Comment by loyess** [comment]
你的域名绑定的是否是你自己的vps的IP?

**Comment by MurrddoL** [comment]
> 你的域名绑定的是否是你自己的vps的IP?
域名是绑定VPS的IP，也用了cloudflare的API ，email，没问题。查了下，也没有其它程序占用443端口。

**Comment by loyess** [comment]
你的Linux版本是？
执行 cat ~/.api/cf.api  对比你的cf的api，是否是Global API Key
cd ~/.caddy/acme/acme-v02.api.letsencrypt.org/sites/xxx.xxx(域名)/  进去这个目录看看，你域名的证书是否生成

**Comment by MurrddoL** [comment]
没错，就是这个global api key。我重装了vps系统，还是不行。

**Comment by loyess** [comment]
Ubuntu 16.04 的系统是32位还是64位？

只支持64位的

执行 uname -m  查看是不是 x86_64

**Comment by MurrddoL** [comment]
root@ip-172-26-0-239:~# uname -m
x86_64

**Comment by loyess** [comment]
你执行 ps aux | grep caddy 

看看你的caddy是不是在运行

**Comment by MurrddoL** [comment]
root@ip-172-26-0-239:~# ps aux | grep caddy
root     27977  0.0  0.4  16572  2108 pts/0    S+   06:38   0:00 grep --color=auto caddy

**Comment by loyess** [comment]
执行 cat /tmp/caddy.log

看caddy日志是什么

**Comment by MurrddoL** [comment]
root@ip-172-26-0-239:~# cat /tmp/caddy.log
Activating privacy features... 2019/10/24 06:41:42 [INFO] [我的域名] acme: Obtaining bundled SAN certificate
2019/10/24 06:41:43 [INFO] [我的域名] acme: Obtaining bundled SAN certificate
2019/10/24 06:41:46 [INFO] [我的域名] acme: Obtaining bundled SAN certificate
2019/10/24 06:41:47 failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many certificates already issued for exact set of domains: 我的域名: see https://letsencrypt.org/docs/rate-limits/, url:

**Comment by loyess** [comment]
这个域名证书申请次数太多了，要等一段时间，你去CF上解析成别的吧，如果你是没有加www的加上www 加了www就去掉www 或者吧www换成其他的

**Comment by MurrddoL** [comment]
我去letsencrypt.org看了下，应该是次数多了，我换别的子域名试试

**Comment by loyess** [comment]
如果你是在同一台vps上用同一个域名仿佛卸载安装，是没有证书申请次数太多的问题的，我并没有在每次卸载都删除证书，只有第一次安装的时候申请证书了，后面的都是复用。

API信息也进行了存储，只需要输入一次，第一次输错了，要修改手动就要修改API的存储文件了，不然即使卸载了，后面再安装时获取的API信息也是错的。

**Comment by MurrddoL** [comment]
明白了，谢谢
