### ISSUE TITLE
利用本脚本xray-plugin升级至V1.8.10的一些疑问

### ISSUE THREAD

**Issue by kfen** [loyess/Shell#122]
xray-plugin升级至V1.8.10原一键脚本配置参数都不能使用了，无论是在手机端还是PC端都无法正常连接，自己也查阅了下上游的一些文档，没看太明白，还望解答，谢谢。

相关文档：https://github.com/teddysun/xray-plugin/issues/18
https://github.com/XTLS/Xray-core/pull/3152
https://xtls.github.io/config/transports/websocket.html#websocketobject

**Comment by RPRX** [comment]
你用的是 WebSocket 的话，如果你 Xray 服务端配置原有 headers host，v1.8.10 开始该值会被用来检查客户端发来的 host

**Comment by cute** [comment]
> 你用的是 WebSocket 的话，如果你 Xray 服务端配置原有 headers host，v1.8.10 开始该值会被用来检查客户端发来的 host

websocket 如果使用非默认端口，则 Host 字段需要包含域名和端口号，中间用冒号 : 分隔。 例如：

`Host: www.example.com:8080`

目前服务端没有正确处理该问题：

[Info] transport/internet/websocket: failed to validate host, request: www.example.com:8080, config:www.example.com
