### ISSUE TITLE
依赖包gettext安装失败，请检查. 

### ISSUE THREAD

**Issue by ackurdeeve** [loyess/Shell#13]
瓦工 debian系统

按任意键开始…或按Ctrl+C取消
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://ftp.debian.org/debian stretch InRelease                                             
Hit:3 http://ftp.debian.org/debian stretch-updates InRelease
Hit:4 http://ftp.debian.org/debian stretch Release 
Reading package lists... Done
[信息] 开始安装依赖包 gettext
[错误] 依赖包gettext安装失败，请检查. 
Checking the error message and run the script again.

**Comment by loyess** [comment]
重试
或
手动安装这些依赖
或
安装rust版本，不需要安装这些依赖。

**Comment by ackurdeeve** [comment]
apt --fix-broken install 应该是更新linux内核后解决
