### ISSUE TITLE
如何设置Nignx来混淆支持 

### ISSUE THREAD

**Issue by xidcn** [loyess/Shell#16]
我在工作机器上已经装有Nignx 和caddy冲突

**Comment by loyess** [comment]
```
server {
    listen 80;
    server_name Example.com;                                   # 你的域名
    return 301 https://$http_host$request_uri;
}
    
server{
    listen 443 ssl;
    server_name Example.com;                                   # 你的域名
    ssl on;
    ssl_certificate /path/to/crt;                              # 证书路径
    ssl_certificate_key /path/to/key;                          # 私钥路径
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout  10m;
    add_header Strict-Transport-Security "max-age=31536000";
    
    location /PATH {                                           # v2ray-plugin的PATH
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_pass http://localhost:PORT;                      # v2ray-plugin端口，作为SS插件运行时填写SS的端口
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    
    location / {
        sub_filter MirrorSite.com Example.com;                 # 镜像站点(不含https://)     你的域名
        sub_filter_once off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Referer https://MirrorSite.com;       # 镜像站点(含https://) 
        proxy_set_header Host MirrorSite.com;                  # 镜像站点(不含https://) 
        proxy_pass https://MirrorSite.com;                     # 镜像站点(含https://)
        proxy_set_header Accept-Encoding "";
    }
}
```

**Comment by xidcn** [comment]
哇 看着头疼

**Comment by xidcn** [comment]
因为宝塔有自带的SSL续签 所以只加了后段 全部贴出来 
最后一段不会填 不知都是自己域名还是伪装域名

server
{
    listen 80;
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
    listen [::]:80;
    server_name live.xidcn.com;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/live.xidcn.com;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/live.xidcn.com/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/live.xidcn.com/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;

    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-56.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/live.xidcn.com.conf;
    #REWRITE-END
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log /dev/null;
    }
    
    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log off;
        access_log /dev/null; 
    }
    access_log  /www/wwwlogs/live.xidcn.com.log;
    error_log  /www/wwwlogs/live.xidcn.com.error.log;

        location /doulala {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:11101;#假设WebSocket监听在环回地址的10000端口上
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        }
        location / {
        sub_filter MirrorSite.com Example.com;                 # 镜像站点(不含https://)     你的域名
        sub_filter_once off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Referer https://MirrorSite.com;       # 镜像站点(含https://) 
        proxy_set_header Host MirrorSite.com;                  # 镜像站点(不含https://) 
        proxy_pass https://MirrorSite.com;                     # 镜像站点(含https://)
        proxy_set_header Accept-Encoding "";
    }
        
        
        
}

**Comment by loyess** [comment]
MirrorSite.com 伪装域名
 Example.com  自己域名
