### ISSUE TITLE
caddy 无法开机自启动

### ISSUE THREAD

**Issue by root9000** [loyess/Shell#17]
系统debian10，重启后通过./ss-plugins.sh restart可以重新启动caddy，但是重启机器不能自启动，没有caddy进程。
查看日志是错误429,查了下是请求频繁？
但是通过过./ss-plugins.sh restart却可以启动

2019/11/16 21:39:26 [INFO] [xxx.com] acme: Obtaining bundled SAN certificate
2019/11/16 21:39:27 failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order......

systemctl status caddy.service
* caddy.service - LSB: A Stable & Secure Tunnel Based On KCP with N:M Multiplexing
   Loaded: loaded (/etc/init.d/caddy; generated)
   Active: active (exited) since Sat 2019-11-16 21:30:12 EST; 13s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 410 ExecStart=/etc/init.d/caddy start (code=exited, status=0/SUCCESS)

**Comment by loyess** [comment]
脚本中没有把caddy的启动脚本文件加到开机启动列表里，之后再修复吧！

**Comment by loyess** [comment]
开机重启没有获取到cf的API参数，启动脚本里面没有写，主脚本里面有获取参数的过程，所以你可以用 ./ss-plugins.sh restart  来启动
