### ISSUE TITLE
请问宝塔该怎么搞 脚本里默认要安装CADDY和ng

### ISSUE THREAD

**Issue by xidcn** [loyess/Shell#19]
请问宝塔该怎么搞 脚本里默认要安装CADDY和ng

**Comment by loyess** [comment]
你可以只用脚本单独安装ss-libev或ss-rust，再手动下载v2ray-plugin，然后修改ss配置，修改宝塔上的web服务器配置。

**Comment by xidcn** [comment]
那么请问v2ray-plugin链接可否给我个
然后安装困难不

**Comment by loyess** [comment]
https://github.com/shadowsocks/v2ray-plugin/releases

**Comment by xidcn** [comment]
老哥我不会安装( •̥́ ˍ •̀ू )
下个版本可以加一个弄去宝塔的链接吗😊
对于小白，宝塔标配啊

**Comment by loyess** [comment]
宝塔太耗资源了，懒得去弄，你把参照我发的nginx的配置写到宝塔里Nginx的配置里面去就行了啊，你可以安装v2ray-plugin的http模式，这样你都不用自己去下载v2ray-plugin了，直接修改/etc/shadowsocks/config.json就行了

**Comment by xidcn** [comment]
哦哦哦 就是先不装ws-tls-web 先装http那个模式
然后再去改配置参数成ws-tls-web是吧😁

**Comment by loyess** [comment]
是这样。

你为什么一定要用宝塔呢？

**Comment by xidcn** [comment]
方便啊 不会敲代码 可视化不是很好嘛

**Comment by xidcn** [comment]
是不是宝塔占用了80
[错误] 检测到80端口被占用，请排查后重新运行.

**Comment by loyess** [comment]
可能是的，宝塔的web服务需要一个端口

**Comment by xidcn** [comment]
我将另一台的参数抄写去新机器/etc/shadowsocks/config.json下

{
"server":"0.0.0.0",
"server_port":11101,
"password":"xidcncom",
"timeout":300,
"user":"nobody",
"method":"rc4-md5",
"fast_open":true,
"nameserver":"8.8.8.8",
"mode":"tcp_and_udp",
"plugin":"v2ray-plugin",
"plugin_opts":"server;path=/uidcla;loglevel=none"
}


然后ng的写法又设置几次都错

**Comment by loyess** [comment]
nginx的配置你是怎么写的？

你可以把另一台的nginx配置复制出来参考

也可以用下面的命令去测试nginx配置是否正确:
`nginx -t -c /path/to/nginx.conf` 

-c 后面接绝对路径

**Comment by xidcn** [comment]
抱歉开了两个单子，中午回复没注意
我现在nginx可以正常反代 已经成功
SS服务目前无连接
下面是/etc/shadowsocks/config.json
{
"server":"0.0.0.0",
"server_port":11101,
"password":"qq464979532qq",
"timeout":300,
"user":"nobody",
"method":"rc4-md5",
"fast_open":true,
"nameserver":"8.8.8.8",
"mode":"tcp_and_udp",
"plugin":"v2ray-plugin",
"plugin_opts":"server;path=/Doulala;loglevel=none"
}

下面是nginx 省略上面其他宝塔自带配置，
        location /doulala {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:11101;#假设WebSocket监听在环回地址的10000端口上
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        }
        location / {
        sub_filter sourceforge.net live.xidcn.com;                 # 镜像站点(不含https://)     你的域名
        sub_filter_once off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Referer https://sourceforge.net;       # 镜像站点(含https://) 
        proxy_set_header Host sourceforge.net;                  # 镜像站点(不含https://) 
        proxy_pass https://sourceforge.net;                     # 镜像站点(含https://)
        proxy_set_header Accept-Encoding "";
    }
        

好像没法生成配置连接，请问上述的配置文件有没有错的地方 


我今天原本打算用甲骨文的白票机搭建一下ws-tls-web-nginx,但是也是安装到最后给我连接了 SS不通 就作罢了

**Comment by xidcn** [comment]
好了好了 ！是我写错了 location /doulala  服务端是Doulala， nginx是doulala
失误失误 ，但是我发现使用./ss-plugins.sh restart 显示的是之前安装的http
超尴尬，
只能手动输入了，先使用看看有没有啥问题。
我之前安装了v2,用了几天，主要是因为听说它用了openssl加密运行库,说是比ss的mbedtls性能高出20%  但是实在是受不了他的代理机制
超级难受

**Comment by loyess** [comment]
嗯嗯，行了就好了，你这安装宝塔也够折腾的。

**Comment by xidcn** [comment]
生命在于折腾 23333

**Comment by xidcn** [comment]
希望下个版本可以加入下这种，如果可以的话

**Comment by loyess** [comment]
nginx有了，caddy有了，不懂有什么理由要加入宝塔再在宝塔上使用nginx。

**Comment by xidcn** [comment]
因为宝塔绑定个域名，设置下nginx只对那个网站起效果，再绑定其它域名之前设置的nginx参数不是继承，该建站建站 该富强富强
