### ISSUE TITLE
请问koolshare的LEDE里面的koolss 该如何配置客户端

### ISSUE THREAD

**Issue by xidcn** [loyess/Shell#23]
koolss 该如何配置客户端，用的ws-tls-web 但是在客户端中好像怎么输入都是错的
不知道是要直接配置文件还是怎么滴 还是说它那个不支持
大佬有玩过吗

**Comment by xidcn** [comment]
[url=https://sm.ms/image/BqoJcn4yOlCUTK3][img]https://i.loli.net/2020/01/18/BqoJcn4yOlCUTK3.png[/img][/url]
[url=https://sm.ms/image/F8Y9wtuDLNxMlGc][img]https://i.loli.net/2020/01/18/F8Y9wtuDLNxMlGc.png[/img][/url]

**Comment by loyess** [comment]
Mux勾选✅上，填写1看看。

**Comment by xidcn** [comment]
> 其他正确填充，最后✅上，填写1看看。

正确填写 也设置了Mux为1 可以PING通 就是不能连接外网

![11.PNG](https://i.loli.net/2020/01/19/iM6wNnPUWJt1BeL.png)

**Comment by lynnial** [comment]
koolss开启tls貌似不能解析域名，你试下服务器地址直接输入节点ip，缺点是动态域名如果更换ip的话需要手动修改
