### ISSUE TITLE
Install shadowsocks-libev the pre-release version 3.3.4 and 秋水逸冰-BBR, will cause installing "getext" failure. 

### ISSUE THREAD

**Issue by ednew2018** [loyess/Shell#24]
Install shadowsocks-libev the pre-release version 3.3.4 and 秋水逸冰-BBR, will cause installing "getext" failure. 

If you run "sudo yum install gettext" by itself. Then it shows "Cannot retrieve metalink for repository: epel/x86_64" error.

I have to force the script to install 3.3.3 as the workaround.

**Comment by loyess** [comment]
CentOS用yum安装工具吧

**Comment by ednew2018** [comment]
哦不好意思，用的是 yum install，这里写错了。。。

**Comment by loyess** [comment]
这个和脚本没多大关系，是你的yum源出问题了
