### ISSUE TITLE
支持quan X

### ISSUE THREAD

**Issue by lyj55r** [loyess/Shell#25]
你好,能不能在v2ray-plugin的插件选项加mux=0的选项,这样quanX也可以使用这个脚本.

**Comment by loyess** [comment]
你先手动修改配置文件用吧，安卓的v2ray-plugin插件暂时还不支持设置mux=0，二选一，让我有点不想去改它。

**Comment by lyj55r** [comment]
好吧！😄

**Comment by loyess** [comment]
已经支持，你试试！

**Comment by lyj55r** [comment]
quan x已经通过测试！可以使用！
