### ISSUE TITLE
是否禁用多路复用(mux)

### ISSUE THREAD

**Issue by xidcn** [loyess/Shell#26]
安装到这步我是默认的，也就是mux=1
然后连接导入出现报错 不知道是缺少什么
请求帮助
https://i.loli.net/2020/02/21/PASCVRUZKME28vt.png

**Comment by loyess** [comment]
ss链接里面的插件名由v2ray改成了v2ray-plugin，你把ss目录下的v2ray.exe改成v2ray-plugin.exe，就可以了。

**Comment by xidcn** [comment]
也就是说 插件名称变了，Windows上改下名称就好了，
安卓上要重装插件还是可以兼容，我看安卓之前的旧版插件也是v2ray而不是v2ray-plugin

**Comment by loyess** [comment]
安卓ss和v2ray-plugin都安装最新版本，新版本能兼容v2ray-plugin。

**Comment by xidcn** [comment]
好的 已经搞好 谢谢
