### ISSUE TITLE
请问显示“该域名在域名服务器处解析的不是本机IP，请确认后再次尝试.”

### ISSUE THREAD

**Issue by cybort** [loyess/Shell#27]
配置好cdn以后，解析到的不是Cloudflare的ip吗，为什么会有这个问题呢？

**Comment by loyess** [comment]
我是计算的cf公开的ipv4的ip段，可能你的cf分给你的ip是没有包含在这个ip段里面吧。

https://www.cloudflare.com/ips-v4

**Comment by cybort** [comment]
确实，返回的是104.28.30和31.xx，不在这个里面

**Comment by loyess** [comment]
你提到的，104开头是cf的ip?  31开头的是vps的ip?

我查了下104开头的是包含在里面的。

**Comment by cybort** [comment]
之前没看清，这样说来104.28确实在范围内啊，有点奇怪

**Comment by loyess** [comment]
可能你当时域名还没有解析完成吧，你可以再试试

**Comment by cybort** [comment]
试了一下，确实不行，而且我试了一下脚本里面获取IP的命令，发现返回的只有ipv6的地址：
 ping cyanbort.top -c 1 2>nul | sed '1{s/[^(]*(//;s/).*//;q}'
2606:4700:3033::681c:1ed1 (2606:4700:3033::681c:1ed1

**Comment by loyess** [comment]
ipv4和ipv6同时存在，不指定的情况下，ping命令 优先获取ipv6了，好吧！我只有ipv4的vps可以测试，没发现这个问题。一会我改改，把它指定ipv4吧。
