### ISSUE TITLE
昨日Update mbedtls to 2.16.5后无法下载，报错了

### ISSUE THREAD

**Issue by cqjerry** [loyess/Shell#28]
ERROR: cannot verify tls.mbed.org's certificate, issued by ‘CN=GlobalSign RSA OV SSL CA 2018,O=GlobalSign nv-sa,C=BE’:
  Unable to locally verify the issuer's authority.
To connect to tls.mbed.org insecurely, use `--no-check-certificate'.

# [Cannot download mbedtls-2.16.5 source. Aborting! ]

**Comment by loyess** [comment]
什么系统？

我用CentOS6的测试时，可以安装！

**Comment by cqjerry** [comment]
ubuntu 18.04
加了--no-check-certificate 参数后可以了。

**Comment by loyess** [comment]
代码中，在下载mbedtls时，有这个参数，你加哪去了？

**Comment by cqjerry** [comment]
我是抄了一部分你的代码到另一个项目中去的。不好意思。

**Comment by loyess** [comment]
Ok
