### ISSUE TITLE
服务器监听地址

### ISSUE THREAD

**Issue by luckykong** [loyess/Shell#3]
ss配置文件中，监听地址，双栈情况下，是不是也应该写成“0.0.0.0”？
写成 ["::","0.0.0.0"]  的情况下，无法启动。

**Comment by loyess** [comment]
[ss-server文档](https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-server.asciidoc)

文档最下面有描述：

> In order to listen to both IPv4/IPv6 address, use the following grammar in your config json file:
> 
> {
> "server":["::0","0.0.0.0"],
> ...
> }

你的vps 存在ipv6吗？

我不确定是不是，需要ipv6和ipv4同时存在，配置文件才会生效；因为我只有ipv4的vps，故而无法确认。

**Comment by luckykong** [comment]
我的vps有v6地址。刚刚又确认了一下，如果同时写有"::0" 和 "0.0.0.0"，无法启动。如果只写v4地址，可以启动

**Comment by loyess** [comment]
上面文档里面的配置，不适用ss-libev

正确配置如下：
> "server":["[::0]", "0.0.0.0"]

请参考：
[ss-server指定监听“::”时，不能同时监听ipv4 #254](https://github.com/shadowsocks/shadowsocks-libev/issues/254)

我在代码里面也是用的这个，我刚把这个换到vps的ss-libev配置里面，是可以运行的。

你看看你是不是忽略了什么，如：结尾的 逗号，或是其它什么...

**Comment by luckykong** [comment]
好神奇。 那我再试试到底怎么回事

**Comment by loyess** [comment]
按照你上面的描述，你写的是这个，如下：

>  ["::","0.0.0.0"] 

正确的是，如下：

> "server":["[::0]", "0.0.0.0"]

我没注意到你的问题的描述是和代码不一样的，这或许才是问题的关键所在...
