### ISSUE TITLE
请问需要什么环境和软件包。纯净系统SS+V2RAY-plugins后无法连接。

### ISSUE THREAD

**Issue by BlackTouma** [loyess/Shell#31]
安装配置如下：

ss-rust+v2ray-plugins

Caddy+TLS+web

搭建完成后，反代的网站可以访问，访问后缀也有 Bad Request 字样。

但小火箭和路由器均无法连接。

同等配置下，GCP原装的Debian9安装正常可以使用。

**Comment by loyess** [comment]
可能是线路问题，另外也和网络运营商有关系，GCP搭建的在移动网络下没什么速度，套CDN可能还有点速度，联通电信的好像还好。

**Comment by BlackTouma** [comment]
我觉得应该不是这个问题。同样环境下 我香港VPS装ss-rust+obfs，速度就非常快。换成ss-rust+v2ray-plugins就直接连不上了。

**Comment by loyess** [comment]
至于你说需要什么系统环境，我只在GCP上测试过，CentOS6+ | Ubuntu16.04+ | Debian9+ 这些都是可以的

**Comment by BlackTouma** [comment]
好的，打扰大佬了，我看看代码自己再摸索下。

**Comment by sportfit** [comment]
this script perfect, it's very well.,thank you very much !   我在debian 9.11搭建了ss libev+v2ray-plugins caddy+wss+tls+web，router同步配置连接，稳定度及速度方面相较于v2ray+wss+tls+web+caddy提升较大。初步搭建好vps查询script，caddy显示running, 测试未能打开反代网站，通过systemctl查询caddy状态，实际并未启动，接下来也简单了，systemctl start caddy启动后，再次systemctl查询及测试，一切OK.
