### ISSUE TITLE
脚本没安装caddy。。之前看到有这个issue，但已经close了

### ISSUE THREAD

**Issue by flhs0606** [loyess/Shell#32]
我是用quic+tls+[cdn]，然后发现没caddy的目录

**Comment by loyess** [comment]
我没在quic模式上加上caddy，所以找不到。

**Comment by flhs0606** [comment]
> 我没在quic模式上加上caddy，所以找不到。

所以是套不了cdn咯。。

**Comment by loyess** [comment]
用含有ws的模式去套cdn吧，quic在cf上申请不了
