### ISSUE TITLE
能否添加对ss-2go版本的支持？感谢

### ISSUE THREAD

**Issue by zaojiapaiwuhao** [loyess/Shell#35]
能否添加对ss-2go版本的支持？因为ss-2go安装时候比较快，又自带ADES。不用编译那么多，感谢。

https://github.com/riobard/go-shadowsocks2    这个是项目地址，麻烦大佬看一下，谢谢

**Comment by loyess** [comment]
用ss-rust版本顶着先？

**Comment by zaojiapaiwuhao** [comment]
> 用ss-rust版本顶着先？

好的，可以，感谢大佬。
