### ISSUE TITLE
shadowsocks rust安装失败

### ISSUE THREAD

**Issue by wangfeng87** [loyess/Shell#36]
buyvm的机器，debain9系统，用脚本默认选择rust版本和kcptun，安装失败
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
chmod: cannot access 'sstunnel': No such file or directory
chmod: cannot access 'sslocal': No such file or directory
chmod: cannot access 'ssserver': No such file or directory
chmod: cannot access 'ssurl': No such file or directory
chmod: cannot access 'ssmanager': No such file or directory
chmod: cannot access 'ssredir': No such file or directory
mv: cannot stat 'sstunnel': No such file or directory
mv: cannot stat 'sslocal': No such file or directory
mv: cannot stat 'ssserver': No such file or directory
mv: cannot stat 'ssurl': No such file or directory
mv: cannot stat 'ssmanager': No such file or directory
mv: cannot stat 'ssredir': No such file or directory

[错误] shadowsocks-rust安装失败.

**Comment by loyess** [comment]
错误看起来是ss-rust的二进制压缩包没有下载下来，你先卸载一遍再重新安装试试，或者执行./ss-plugins.sh script 查看脚本是否是最新的。
