### ISSUE TITLE
您好，我咨询一下这些启动命令怎么用

### ISSUE THREAD

**Issue by a28257632** [loyess/Shell#39]
选项<options>包括:
        install          安装
        uninstall        卸载
        update           升级
        start            启动
        stop             关闭
        restart          重启
        status           查看状态
        script           升级脚本
        show             显示可视化配置
        uid              为cloak添加一个新的uid用户
        link             用新添加的uid生成一个新的SS://链接
        scan             用ss://链接在当前终端上生成一个可供扫描的二维码
        help             打印帮助信息并退出

因为每次服务器重启，服务就自动停止了，不知道用什么命令可以重新启动服务！

**Comment by a28257632** [comment]
还有苹果手机Quantumult X可以使用v2ray-plugin吗，因为如何设置，目前只能在Shadowrocket中使用，而且速度很慢

**Comment by loyess** [comment]
比如使用重启命令
```
./ss-plugins.sh restart
```

QuanX 使用v2ray-plugin, 必须要禁用mux , 它不支持mux。然后，直接导入ss:// 开头的链接进QuanX就能使用。

**Comment by a28257632** [comment]
好的，感谢，QuanX不支持443端口，请问我该如何修改默认端口？谢谢回复

**Comment by a28257632** [comment]
经过测试，好像QuanX可以支持443端口，禁用了Mux以后Shadowrocket中无法使用，这个应该是通病，大佬知道Surge能使用v2ray-plugin吗？他应该如何配置，如果知道麻烦告知一下，感谢您

**Comment by loyess** [comment]
Surge没用过，你可以自己测试一下。

**Comment by a28257632** [comment]
有tg号码，可以加个好友吗，有不懂的可以询问您一下。
