### ISSUE TITLE
支不支持centos 7

### ISSUE THREAD

**Issue by 1608637229** [loyess/Shell#4]
问一哈。

**Comment by 1608637229** [comment]
另外也就是说类似于ssr的http-simple只能用废弃的插件simple-obfs对吧。

**Comment by loyess** [comment]
Ubuntu CentOS Debian 这三个64位的Linux 系统都支持！

**Comment by loyess** [comment]
除了kcptun是用来加速的，其它的都是混淆插件！

**Comment by 1608637229** [comment]
> 除了kcptun是用来加速的，其它的都可看成是混淆插件！

Usage: 
./ss-plugins.sh [-O|-L|-H] [install|uninstall|update|start|stop|restart|status|show|uid|link|scan] [new_uid|ss_link]
这个该怎么用，用了老是提示help，比如我要重启ss该怎么输入命令

**Comment by loyess** [comment]
./ss-plugins.sh -O restart

**Comment by 1608637229** [comment]
> ./ss-plugins.sh -O restart

你这个我以为是-L一直加-L我以为是对于第二个中括号里的。。。

**Comment by loyess** [comment]
-L 是你要把整个GitHub里面的代码clone 下来，本地运行的指令，方便我在Linux里面测试代码用的。

当然你不嫌麻烦的话，也可以clone下来所有代码本地安装。

一般用-O 命令，其它的代码从GitHub在线获取就行了。

**Comment by 1608637229** [comment]
> ./ss-plugins.sh -O restart

我觉得你可以在 ./ss-plugins.sh增加第四个选项菜单，|update|start|stop|restart|status|show把这几个常用的放到二级菜单里。

**Comment by 1608637229** [comment]
> 除了kcptun是用来加速的，其它的都可看成是混淆插件！

我测试了下，确实可以。安装v2ray插件后，选择websocket-http。然后装手机上插件，插件的hostname填入host。就能达到ssr的http-simple的功能了，我只是测试下能够实现电信卡的伪装免流功能。ss加上插件已经完全取代ssr了也可以部分代替v2ray了。开源软件还是厉害啊

**Comment by loyess** [comment]
我已经更新了脚本，去掉了-O和-L参数，改为自动判断是在线安装还是本地安装了，你删除原来的脚本，重新下载一遍就可以使用了
