### ISSUE TITLE
特来感谢大佬

### ISSUE THREAD

**Issue by zaojiapaiwuhao** [loyess/Shell#40]
特来感谢大佬，上次只是提一次 需要go-ss2脚本，今天用脚本发现加进去了。非常感谢.

**Comment by zaojiapaiwuhao** [comment]
刚测试了一下，虽然安装好，但是显示未启动，大便9.0系统
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
 Go-shadowsocks2一键脚本 [v2.4.7 Online]

    1. BBR
    2. Install
    3. Uninstall
     
grep: grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
warning: GREP_OPTIONS is deprecated; please use an alias or script
 当前状态: 已安装 但 未启动

**Comment by loyess** [comment]
GREP_OPTIONS从grep 2.21开始不推荐使用，如果您使用此解决方案，则会看到以下警告：

`grep: warning: GREP_OPTIONS is deprecated; please use an alias or script`

方案一：
```
sudo -i
vim ~/.bashrc 或 vim ~/.bashrc

找到 export GREP_OPTIONS='....xxx....' 
用 # 注释掉，或者将其改成 alias grep='....xxx....'
```
方案二：
```
sudo -i
unset GREP_OPTIONS
```

**Comment by zaojiapaiwuhao** [comment]
我只开了BBR PLUS  GO-SS2 协议GCM256  其他都没有选，默认的。可能跟系统有关吧。商家的系统问题

**Comment by loyess** [comment]
查看进程：ps aux | grep go-shadowsocks2
查看日志：tail -f /var/log/go-shadowsocks2.log

你用上面的命令查看看看，也许进程是启动的，另外也看日志有没有报啥错。

**Comment by loyess** [comment]
缺少安装jq，修复了。

`./ss-plugins.sh script` 

更新脚本，再次安装就可以了。
