### ISSUE TITLE
ss-libev 配置文件不能修改

### ISSUE THREAD

**Issue by sylee23** [loyess/Shell#42]
修改config.json文件之后重启ss会失败，还是说配置文件不可以修改呢

**Comment by sylee23** [comment]
更改为如下
{
        "server":"0.0.0.0",
        "port_password":{
                "123":"asdf",
                "1234":"asdf",
                "12345":"password",
                "7555":"password"
                },
        "nameserver":"127.0.0.1",
        "timeout":300,
        "method":"chacha20",
        "plugin":"obfs-server",
        "plugin_opts":"obfs=tls"
}

**Comment by loyess** [comment]
脚本没有限制你修改配置文件，不能启动只能说明它本身就不支持你修改的这种配置，再多试试。

**Comment by sylee23** [comment]
我之前自己搭建的时候用的一模一样的配置，我再试一试

**Comment by sylee23** [comment]
> 脚本没有限制你修改配置文件(go-ss2除外)，不能启动，可能它本身就不支持你修改的这种配置，或者，可能某些字段有问题，也可能不能搭配插件一起使用，再多试试。

我貌似找到问题了
https://github.com/shadowsocks/simple-obfs/issues/244

**Comment by loyess** [comment]
把启动脚本中的ss-server改成ss-manager，自己测试吧
