### ISSUE TITLE
Gost tunnel plugin

### ISSUE THREAD

**Issue by ingnelson** [loyess/Shell#44]
Hello sir.

Can you add gost tunnel plugin , please ? 
Gost tunnel:
https://github.com/ginuerzh/gost

Gost plugin for android
https://github.com/xausky/ShadowsocksGostPlugin

I would like to use this plugin in my Android but it is a little complicated for me . You have the knowledge to create a script for us to install it . Please .

You are doing a greater work, because there are many people who are not programmer but want to use those plugin and you create the script to install it more easy thank.

**Comment by loyess** [comment]
I think you should search for Gost's one-click script

Because when using ShadowsocksGostPlugin, on the server side, Gost does not need to run as a plugin for Shadowsocks.
