### ISSUE TITLE
无法更新，命令无法使用

### ISSUE THREAD

**Issue by immrsui** [loyess/Shell#45]
命令无法使用
[root@vultr ~]# ./ss-plugins.sh
./ss-plugins.sh: line 1600: syntax error near unexpected token `=='
./ss-plugins.sh: line 1600: `esac == "menu" ]]; then'
重新部署的话提示
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 416 Range Not Satisfiable

    The file is already fully retrieved; nothing to do.
我该怎么办？

**Comment by loyess** [comment]
试试执行下面的命令更新脚本：
```
./ss-plugins.sh script
```

或者，先把本地 ss-plugins.sh 文件删除后，再重新下载：
```
wget -N --no-check-certificate -c -t3 -T60 -O ss-plugins.sh https://git.io/fjlbl
chmod +x ss-plugins.sh
./ss-plugins.sh
```
