### ISSUE TITLE
[提示] caddy is already installed but not running.

### ISSUE THREAD

**Issue by xidcn** [loyess/Shell#46]
debian9 安装以后没有启动，并且怎么弄都不启动 怎么办，已经重装多次也不行，./ss- plugins.sh restart 启动显示成功，其实没成功

/caddy/acme/acme-v02.api.letsencrypt.org/users/*******@gmail.com 下有域名证书
/usr/local/caddy/Caddyfile 下配置无问题
执行ps aux | grep caddy 显示
root@hei:~# ps aux | grep caddy
root     18622  0.0  0.1  12780   960 pts/0    S+   18:03   0:00 grep caddy
看不到日志
cat: /tmp/caddy.log: No such file or directory

root@ru:~# ./ss-plugins.sh restart
Stopping Shadowsocks-libev success
Stopping v2ray-plugin success
Stopping caddy success
Starting Shadowsocks-libev success
Starting v2ray-plugin success
Starting caddy success
root@ru:~# ./ss-plugins.sh status
[信息] shadowsocklibev-libev (pid 21872) is already running.
[信息] v2ray-plugin (pid 21878) is already running.
[提示] caddy is already installed but not running.``

**Comment by xidcn** [comment]
https://i.loli.net/2020/06/10/hwNok3yYzdVUXHZ.jpg

**Comment by loyess** [comment]
执行卸载后重新安装试试

如果启动失败, 执行下面命令查看日志。
```
./ss-plugins.sh log
```

日志文件存储路径有变动，如下：
```
    SS-libev日志文件：/var/log/shadowsocks-libev.log
    SS-rust日志文件：/var/log/shadowsocks-rust.log
    Go-ss2日志文件：/var/log/go-shadowsocks2.log
    kcptun日志文件：/var/log/kcptun.log
    cloak日志文件：/var/log/cloak.log
    rabbit-tcp日志文件：/var/log/rabbit-tcp.log
    caddy错误日志文件：/var/log/caddy-error.log
    caddy访问日志文件：/var/log/caddy-access.log
    nginx错误日志文件：/var/log/nginx-error.log
    nginx访问日志文件：/var/log/nginx-access.log

```

**Comment by blaisewang** [comment]
我也遇到了这个问题，系统是 Debian 10，似乎是 acme 的问题，
解决方案是用 root 用户安装，而不是 sudo ./ss-plugins.sh
