### ISSUE TITLE
感谢，这个脚本实在太强了。。。

### ISSUE THREAD

**Issue by tunlong** [loyess/Shell#47]
感谢，这个脚本实在太强了。。。暂时没有遇到问题。

**Comment by loyess** [comment]
一般般，只是保证能用，代码其实写的很垃圾。

**Comment by tunlong** [comment]
你太谦虚了，插件里的V2RAY对我们小白有多复杂，还要申请证书还要啥的，现在能一次性搞定实在太好了。
