### ISSUE TITLE
teddysun_New-v2ray-plugin

### ISSUE THREAD

**Issue by kfen** [loyess/Shell#49]
https://github.com/teddysun/v2ray-plugin/releases

由于https://github.com/shadowsocks/v2ray-plugin，

更新较为滞后，teddysun在推上说明自己打算跟进。

**Comment by kfen** [comment]
冒昧的问下作者，能不能这样，脚本代码进行版本高低的比对，有些升级版本高的那一个~

**Comment by loyess** [comment]
自己尝试编译最新版本，替换旧版本的二进制文件。

如果使用v2ray-plugin速度稳定，又没有出现非升级不可的bug，是不是最新版本似乎意义不大。

**Comment by loyess** [comment]
或者，干脆把获取源改成teddysun版本的？

**Comment by kfen** [comment]
> 或者，干脆把获取源改成teddysun版本的？
> 
> 就我个人来说，最新不最新倒是没所谓。

近期考虑升级主要原因还是考虑在安全性上，V2ray-core最近不是爆出严重的安全问题，导致大修了几次版本号嘛，所以.......

**Comment by loyess** [comment]
官方版本的v2ray-plugin，受影响的严重bug有跟进过了的。

**Comment by loyess** [comment]
[Change v2ray-plugin binary source](https://github.com/loyess/Shell/commit/a271ee85d84a77603d2aa4f9f8258e229fd6a56f)
