### ISSUE TITLE
ss-server log 在哪里？

### ISSUE THREAD

**Issue by ednew2018** [loyess/Shell#5]
/var/log 里没找到。不知道是ssr-libev的原因还是这个脚本的原因。

**Comment by loyess** [comment]
ss-libev似乎只能输出错误日志，有些插件日志输出倒是比较全面，但是我没有去指定它输出，全部丢到Linux黑洞里面去了。

**Comment by ednew2018** [comment]
thx

**Comment by ednew2018** [comment]
我看ssr-libev上说加-v就行

shadowsocks-libev_centos.sh
```
$DAEMON -c $CONF -v > /var/log/shadowsocks-libev.log 2>&1 &
```

**Comment by loyess** [comment]
没试过这个参数，只知道-v是获取版本号的。
