### ISSUE TITLE
安装完成后 caddy 反代网站打不开

### ISSUE THREAD

**Issue by xidcn** [loyess/Shell#50]
安装完成后 ss工作正常，就是打开郁闷打不打，重装2次都这样，麻烦看看

**Comment by xidcn** [comment]
全新安装v2ray，选ws-tls-web 一路操作好之后，ss可以正常使用，但是你访问域名的时候，并没有反代成功，返回了502错误，还有之前没动过的旧版 访问了域名看了下，也是502了，完全没动过参数

**Comment by xidcn** [comment]
大佬 怎么弄？我没懂啊

**Comment by loyess** [comment]
卸载重装就可以了
