### ISSUE TITLE
建议将判断IP的方法改为直接nslookup用户输入的域名

### ISSUE THREAD

**Issue by NyaRabbit** [loyess/Shell#51]
是这样的。

我的AWS服务器，eth0接口IP是172.X.X.X

但是我从外网连进来时，是走了大陆中转的，IP却是183.X.X.X

然后脚本就一直提示输入的域名不对（未被解析），请检查解析结果。

希望修复这个问题（将判断用户输入的域名是否已经解析的方法，改成直接nslookup用户输入的域名）。

**Comment by loyess** [comment]
感谢反馈， [Fix #51](https://github.com/loyess/Shell/commit/defd486b5b6a20af90416b3bbf4a762edad4dbd6) 尝试修复了一下.

不知是否可行，你可以测试下。

**Comment by NyaRabbit** [comment]
> 
> 
> 感谢反馈， [Fix #51](https://github.com/loyess/Shell/commit/defd486b5b6a20af90416b3bbf4a762edad4dbd6) 尝试修复了一下.
> 
> 不知是否可行，你可以测试下。

可以了，谢谢w
