### ISSUE TITLE
如果自己的域名本身有证书 怎么设置？

### ISSUE THREAD

**Issue by immrsui** [loyess/Shell#53]
1如果自己的域名本身有证书 怎么设置？
本身申请过长期证书的。需要提前做什么工作。
2，可以绑定2个域名吗？

**Comment by loyess** [comment]
1. 安装过程中，没有提供手动指定证书路径的选项，如果你想指定自己的证书，只能自己去编辑修改配置文件了。

2. 两个域名是要用在什么场景？

**Comment by immrsui** [comment]
因为最近总是证书订单创建失败，但是我郁闷本来有一个长期证书，所以才想着可否手动指定证书。
[信息] 开始生成域名 woshichaojivip.ml 相关的证书 

[Wed Jul 15 01:16:48 UTC 2020] Single domain='woshichaojivip.ml'
[Wed Jul 15 01:16:48 UTC 2020] Getting domain auth token for each domain
[Wed Jul 15 01:16:49 UTC 2020] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Wed Jul 15 01:16:49 UTC 2020] Please add '--debug' or '--log' to check more details.
[Wed Jul 15 01:16:49 UTC 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

[信息]请根据上方提示，去Cloudflare上添加txt记录，完成后按任意键开始。
[信息]如果出现“too many certificates already issued for exact set of domains”错误，请按Ctrl+C终止。

**Comment by loyess** [comment]
这个是该域名短期内证书申请次数过多，导致证书申请受限，换成其他子域名，例如：带 www 前缀，或其它。
