### ISSUE TITLE
安装脚本似乎出现了问题

### ISSUE THREAD

**Issue by root9000** [loyess/Shell#54]
[信息] 下载mbedtls-2.16.7.
mbedtls-2.16.7-gpl.tgz 当前目录中不存在, 现在开始下载.
--2020-07-24 22:36:26--  https://tls.mbed.org/download/mbedtls-2.16.7-gpl.tgz
Resolving tls.mbed.org (tls.mbed.org)... 79.170.91.36
Connecting to tls.mbed.org (tls.mbed.org)|79.170.91.36|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-24 22:36:27 ERROR 404: Not Found.

[错误] 下载 mbedtls-2.16.7-gpl.tgz 失败.
root@VM:~# wget https://tls.mbed.org/download/mbedtls-2.16.7-gpl.tgz
--2020-07-24 22:39:15--  https://tls.mbed.org/download/mbedtls-2.16.7-gpl.tgz
Resolving tls.mbed.org (tls.mbed.org)... 79.170.91.36
Connecting to tls.mbed.org (tls.mbed.org)|79.170.91.36|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-24 22:39:15 ERROR 404: Not Found.

**Comment by loyess** [comment]
Fixed [f7dc44d](https://github.com/loyess/Shell/commit/f7dc44d8aaf1bdf69531271af69ffca803854943)
