### ISSUE TITLE
caddy检查更新出错

### ISSUE THREAD

**Issue by root9000** [loyess/Shell#55]
需要重新安装么？

root@VM:~# ./ss-plugins.sh update
[信息] 正在进行版本比对请稍等.
[提示] shadowsocklibev-libev当前已是最新版本3.3.4不需要更新.
[提示] v2ray-plugin当前已是最新版本1.3.4不需要更新.
/dev/fd/63: line 327: /usr/local/caddy/caddy.v: No such file or directory

**Comment by loyess** [comment]
#####方案1：
> 卸载重装

#####方案2：
caddy1执行指令:
```shell
echo '1,1.0.4' > /usr/local/caddy/caddy.v
```

caddy2执行指令:
```shell
echo '2,2.1.1' > /usr/local/caddy/caddy.v
```
