### ISSUE TITLE
安装报错 求助

### ISSUE THREAD

**Issue by Meilinhost** [loyess/Shell#56]
一路操作都显示 curl: /usr/local/lib/libcurl.so.4: no version information available (require

![捕获.JPG](https://i.loli.net/2020/07/30/uZ6UKPOpQYJ5DH1.jpg)

**Comment by loyess** [comment]
用下面这一段去Google解决吧！
```
curl: /usr/local/lib/libcurl.so.4: no version information available
```

脚本没啥问题！

**Comment by Meilinhost** [comment]
> 用下面这一段去Google解决吧！
> 
> ```
> curl: /usr/local/lib/libcurl.so.4: no version information available
> ```
> 
> 脚本没啥问题！

修好了curl报错，但是脚本问题还是依旧
大佬！
![Screenshot_20200730-205959.jpg](https://i.loli.net/2020/07/30/2uodzYwaqvZSUXj.jpg)


![Screenshot_20200730-205531.jpg](https://i.loli.net/2020/07/30/HdUsVM4ezDpoS1Q.jpg)

**Comment by loyess** [comment]
刚在全新的CentOS 8上安装ss-libev成功。

**Comment by Meilinhost** [comment]
好的，我是debian9 之前没这情况，就是昨天DD系统之后，重装遇到的这些问题，因为我有宝塔nginx，所以我依旧用你直接告诉我的办法，安装ws-http让它部署v2ray下来，然后去配置文件改参数成ws-tls-web 一直都好用，这次卡机了，我看报错没有说少什么组件还是什么的 完全没看懂，所以我还是得向你提问 @loyess

**Comment by loyess** [comment]
@Meilinhost  我也不清楚你是哪里出问题了，如果实在不行，我建议安装rust和go版ss，因为这两个都是拉取的现成的二进制文件，不用编译也不需要安装大量的依赖，套插件用的我觉得用哪个版本的ss都一样，另外rust版本的还有none加密方式，ss-android项目也是将ss的libev库换成了rust库了。
