### ISSUE TITLE
ERROR 404: Not Found.

### ISSUE THREAD

**Issue by mercik** [loyess/Shell#57]
shadowsocks-libev-3.3.4.tar.gz [已存在.]
shadowsocks-libev 当前目录中不存在, 现在开始下载.
--2020-08-02 18:00:56--  https://github.com/loyess/Shell/raw/master/service/shadowsocks-libev_centos.sh
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-02 18:00:57 ERROR 404: Not Found.

[错误] 下载 shadowsocks-libev 失败.

**Comment by loyess** [comment]
请更新脚本：

` ` `shell
./ss-plugins.sh script
` ` `
