### ISSUE TITLE
大佬 nginx配置文件地址换了吗?

### ISSUE THREAD

**Issue by Meilinhost** [loyess/Shell#58]
/etc/nginx/nginx.conf没有这个路径啊
是不是换地址了

**Comment by Meilinhost** [comment]
@loyess

**Comment by loyess** [comment]
@Meilinhost 配置文件没有换

**Comment by Meilinhost** [comment]
> @Meilinhost配置文件没有换

那就是没有安装上nginx好像

**Comment by loyess** [comment]
@Meilinhost ，我确认安装nginx是没有问题的。

另外，nginx由于是直接用的apt和yum安装的，一些较低版本的系统上会有问题，因为启动的时候是用的 Systemd 进行管理的，也就是
 systemctl 指令，较老版本的系统上没有这玩意，nginx这块不准备去做老版本兼容了，用新版本系统就行。

Nginx配置这块还可以改进，但我一直用的都是caddy，也就没折腾nginx了。

**Comment by Meilinhost** [comment]
@loyess 
我刚刚是debian9没有安装nginx成功，我再试试centos7

**Comment by loyess** [comment]
@Meilinhost 你安装完成后，可以向上滚动终端屏幕，看看上面的安装记录！如果出错了上面应该有记录！

**Comment by loyess** [comment]
@Meilinhost Debian 9是可以安装的

**Comment by Meilinhost** [comment]
@loyess  我看来下debian9 刚刚报错是这个

/dev/fd/63: line 2: /etc/nginx/nginx.conf: No such file or directory
Failed to start nginx.service: Unit nginx.service not found.

**Comment by loyess** [comment]
只有这么点记录么？

**Comment by Meilinhost** [comment]
@loyess 
debian9报错的就这些吧 应该说是没有显示“nginx安装成功”这个提示

**Comment by Meilinhost** [comment]
> 只有这么点记录么？

@loyess  centos7 安装正常

**Comment by loyess** [comment]
那可能是Debian系统被你折腾出了什么问题了吧！

**Comment by Meilinhost** [comment]
@loyess 哦对了大佬！问你个事情
之前安装这个 两端都跑一样的分数（ytb）这次就发现手机跑不过电脑，不知道是我配置错了还是怎么的，
所以我就安装这次nginx查一下参数，有遇到这种情况吗？我只值得v2rayng会出现这种情况，SS这次也出现这种情况 不知道是不是个例

**Comment by Meilinhost** [comment]
> 那可能是Debian系统被你折腾出了什么问题了吧！

@loyess  可能是吧 我也懵逼 最近提问的都是再debian9下面出现的问题

**Comment by loyess** [comment]
没去注意测速这块，如果你发现nginx配置可以优化，可以在这里反馈，提出删哪或者加哪就行！

**Comment by Meilinhost** [comment]
> 没去注意测速这块，如果你发现nginx配置可以优化，可以在这里反馈，提出减少哪一个或哪哪行！

@loyess  好的
