### ISSUE TITLE
wget: missing URL

### ISSUE THREAD

**Issue by mercik** [loyess/Shell#59]
shadowsocks-libev-3.3.4.tar.gz [已存在.]
shadowsocks-libev 当前目录中不存在, 现在开始下载.
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
[错误] 下载 shadowsocks-libev 失败.

**Comment by loyess** [comment]
还没解决？

**Comment by mercik** [comment]
decided everything is in order! Thanks for your work
