### ISSUE TITLE
安装cloak后SS无法连接，安装goquiet后SS连接正常

### ISSUE THREAD

**Issue by Azvuk** [loyess/Shell#6]
安装cloak后SS无法连接，卸载重新安装goquiet后SS连接正常。
安装cloak后，端口显示为43，但实际是443。

![Snipaste_2019-09-23_19-40-36](https://user-images.githubusercontent.com/55695461/65422912-5100ff00-de3a-11e9-95ad-1b77143f8062.png)

**Comment by loyess** [comment]
你ss配置文件也是43吗？看一下配置文件吧

**Comment by loyess** [comment]
不行你就把脚本删除，重新下载脚本，我刚刚更新脚本修改代码出了bug，已经修复了，你重新下载脚本，执行卸载再安装，重新试试。

**Comment by Azvuk** [comment]
SS配置文件是443，但还是无法连接。好的，我重新下载脚本试试。

**Comment by loyess** [comment]
可以连接，就是那里少了个4，可能被我误删了，我一会改改

**Comment by loyess** [comment]
多了个 $ 符号，把一个4给吞了，修复了

**Comment by Azvuk** [comment]
奇怪，还是连接不上，卸载装其它人的Cloak一键脚本也连接不上，但是goquiet就可以，不知为什么

**Comment by loyess** [comment]
你用什么客户端？

**Comment by Azvuk** [comment]
windows端，win7 64

**Comment by loyess** [comment]
你下载2.0.2版本的windows的cloak，你可能下载的是最新版本的cloak，我锁定在2.0.2版本了，这个总是有变动，暂时没想更新它

**Comment by Azvuk** [comment]
删掉了最新的2.1.1，换成了2.0.2的cloak，还是不行

**Comment by loyess** [comment]
我刚才已经试着安装过了，连接是正常的

**Comment by loyess** [comment]
我刚才又试了一遍，可用

**Comment by Azvuk** [comment]
你用的是Debian还是Ubuntu还是Centos？

**Comment by loyess** [comment]
我测试的是Debian

**Comment by WilhelmZhu** [comment]
脚本应该是没问题的，我两个vps，有个跑了v2ray+ws再用ss+cloak的话，ss连不上；另一个没有跑其他的vps，可以用ss+cloak连接的上。

**Comment by loyess** [comment]
我试了下CentOS也是可以用的！可能你哪里出错了

**Comment by loyess** [comment]
@WilhelmZhu 端口占用了 都用的443

**Comment by WilhelmZhu** [comment]
@loyess 对，但我改ckserver配置自定义端口，还是没用。
所以我改成用v2raycore+ws外加ss+v2ray plugin了，ngingx配置改下就OK了。

**Comment by loyess** [comment]
@WilhelmZhu  因为我固定了cloak的端口只能用443，因为我觉得如果改成别的端口，那么用这个插件就没多大意义了

**Comment by WilhelmZhu** [comment]
@loyess 哈哈确实呢

**Comment by loyess** [comment]
@Azvuk  我更新了cloak到最新版，你可以试试看

**Comment by Azvuk** [comment]
奇怪，还是不行，把 插件程序 和 插件选项 从SS服务器配置删掉就能连接上，加上就不行了。
换了一台Win10的电脑试，也是不行。可能和服务器或者Debian的版本有关？

**Comment by loyess** [comment]
不清楚你的问题出在哪里，我试装的几个都连接正常，你先用着goquiet吧！

**Comment by loyess** [comment]
@Azvuk  你用的是哪家的服务器？

**Comment by windstander** [comment]
我发现SS RUST加cloak插件不能使用，但是SS LIBEV可以。

**Comment by windstander** [comment]
> 
> 
> 不清楚你的问题出在哪里，我试装的几个都连接正常，你先用着goquiet吧！

你是用的哪个版本的SS？

**Comment by loyess** [comment]
> 我发现SS RUST加cloak插件不能使用，但是SS LIBEV可以。

ss-rust + cloak 测试（Android）过了，可以用。

> 你是用的哪个版本的SS？

3个版本都用。


如果仍不能使用，请检查客户端是否为最新版本！
