### ISSUE TITLE
centos8 安装使用脚本安装后无法访问

### ISSUE THREAD

**Issue by EricMzky** [loyess/Shell#60]
centos8，瓦工，纯净系统。执行ss文件，选择ss-libev，v2-pl，步骤如下：
请选择要安装的Shadowsocks插件
|21:08:27|
|21:08:27|  1. v2ray-plugin
|21:08:27|  2. kcptun
|21:08:27|  3. simple-obfs
|21:08:27|  4. goquiet
|21:08:27|  5. cloak
|21:08:27|  6. mos-tls-tunnel
|21:08:27|  7. rabbit-tcp
|21:08:27|  8. simple-tls
|21:08:27|
|21:08:29|(默认: 不安装)：1
|21:08:30|
|21:08:30|请为v2ray-plugin选择 Transport mode
|21:08:30|
|21:08:30|  1. ws+http
|21:08:30|  2. ws+tls+[cdn]
|21:08:30|  3. quic+tls+[cdn]
|21:08:30|  4. ws+tls+web
|21:08:30|  5. ws+tls+web+cdn
|21:08:30|
|21:08:32|(默认: ws+http):4
|21:08:32|
|21:08:32|  over = ws+tls+web
|21:08:32|
|21:08:33|请选择一个Web服务器
|21:08:33|
|21:08:33|  1. caddy
|21:08:33|  2. nginx
|21:08:33|
|21:08:34|(默认：caddy):
|21:08:34|
|21:08:34|  web = caddy
|21:08:34|
|21:08:34|请选择Caddy软件包版本
|21:08:34|
|21:08:34|  1. Caddy
|21:08:34|  2. Caddy2
|21:08:34|
|21:08:35|(默认：Caddy):
|21:08:35|
|21:08:35|  version = Caddy

mirror_site = https://kernel.ubuntu.com

之前一直很好用，突然最近几天无法访问，按照之前步骤重新配置。个人域名绑定解析无问题。分流为ubuntu网址。之后安装顺利无错误。但是就是无法使用，无法Q，访问GG终止连接。ping IP通，无问题。

以上重装重新安装配置脚本执行大于7次。
请指导！谢谢！

**Comment by loyess** [comment]
电脑访问不了，还是手机？安卓端吗？

安卓端ss和v2ray-plugin版本是多少？

服务端查看下日志是啥 ./ss-plugin.sh log

**Comment by EricMzky** [comment]
> 电脑访问不了，还是手机？安卓端吗？
> 
> 安卓端ss和v2ray-plugin版本是多少？
> 
> 服务端查看下日志是啥 ./ss-plugins.sh log

电脑，手机都访问不了。ios 小飞机 连通性测试，红色断开。电脑端切换该节点无法访问。 纯净centos8系统，无任何其他东西。通过ss脚本安装v2，版本未知

**Comment by loyess** [comment]
没发现有什么问题，我刚用CentOS 8搭建了，用小火箭测试可以正常使用，小火箭版本是：2.1.61

安卓端也测试了，可以正常使用，ss-android版本:5.1.3 ，v2ray-plugin版本：1.4.2

电脑端未测试，想来也是一样的。

**Comment by EricMzky** [comment]
> 没发现有什么问题，我刚用CentOS 8搭建了，用小火箭测试可以正常使用，小火箭版本是：2.1.61
> 
> 安卓端也测试了，可以正常使用，ss-android版本:5.1.3 ，v2ray-plugin版本：1.4.2
> 
> 电脑端未测试，想来也是一样的。

那就奇怪了！我装了七八遍，今天试了一下 其他脚本 ss的不加v2 就跑通了。我在找一下原因！谢谢啦～
