### ISSUE TITLE
SS Rust does not work on Vultr and Greencloud

### ISSUE THREAD

**Issue by windstander** [loyess/Shell#63]
I have tried many times and it only succeeded on Lightsail.
Failed on Vultr and Greencloud.
Below are errors.  Installed but not working, even after rebooting both services:
![WOZ53N~)ZNEZ{$CRRYTE 3D](https://user-images.githubusercontent.com/55864125/100584895-adf22200-3327-11eb-8f0b-333d5b43de84.png)
![N8SX C6BV}WNZ(8S(A7) QL](https://user-images.githubusercontent.com/55864125/100584906-b2b6d600-3327-11eb-99f1-27bbabfa42f4.png)

**Comment by windstander** [comment]
![Uploading 0KA_A67(34WR5L0QA[GEN)0.png…]()

**Comment by windstander** [comment]
![0KA_A67(34WR5L0QA GEN)0](https://user-images.githubusercontent.com/55864125/100587971-383c8500-332c-11eb-816a-cdcd99796508.png)

**Comment by loyess** [comment]
抱歉，根据你提供的图文，我找不出问题出在哪。
我手上也没有 Vultr 和 Greencloud 的 Vps 供我测试，我仅在Google家的vps上测试过，能正常运行。

**Comment by windstander** [comment]
> 抱歉，根据你提供的图文，我找不出问题出在哪。
> 我手上也没有 Vultr 和 Greencloud 的 Vps 供我测试，我仅在Google家的vps上测试过，能正常运行。

那我建一个Vultr服务器给你试一下怎么样？

**Comment by windstander** [comment]
这里能给你发私信吗？

**Comment by windstander** [comment]
> 
> 
> 抱歉，根据你提供的图文，我找不出问题出在哪。
> 我手上也没有 Vultr 和 Greencloud 的 Vps 供我测试，我仅在Google家的vps上测试过，能正常运行。

又试了很多次，跟Cloak没有关系，只安装rust都是不能启动，手动启动也是abort的结果，怪了。

**Comment by windstander** [comment]
日志显示json parse error，是配置文件有问题？

**Comment by loyess** [comment]
你执行命令 uname -m 结果是 x86_64 吗？

另外，你用下面命令，看看配置文件是不是有什么问题。
`cat /etc/shadowsocks/config.json`

**Comment by windstander** [comment]
![HU)I{Y~(QYP0B$9EFRAKG3F](https://user-images.githubusercontent.com/55864125/101120155-ddef3d00-3627-11eb-8cf7-11c641c975b1.png)
![(SO_II`E9 AI2)NDCE%57}N](https://user-images.githubusercontent.com/55864125/101120166-e182c400-3627-11eb-8848-6639a016bcf0.png)

服务器是X86_64没有问题。
上面是在Vultr测试的截图，安装后有报错，再调阅配置文件，第一排server格式明显是错的。
另经测试Linode可以成功。

> 
> 
> 你执行命令 uname -m 结果是 x86_64 吗？
> 
> 另外，你用下面命令，看看配置文件是不是有什么问题。
> `cat /etc/shadowsocks/config.json`

**Comment by windstander** [comment]
已确认将config.json的服务器信息修改为
"server":"0.0.0.0",
后，运行正常，解决了。

**Comment by windstander** [comment]
另外建议脚本安装cloak插件的时候，设置redirect IP可以设置为域名，不是IP，这样即使那个要伪装的网站的IP变了也不影响。

**Comment by loyess** [comment]
`ss-rust`版本是不会使配置文件 `server` 字段变成 `["[::0]","0.0.0.0"]` ，代码中只判断了 `ss-libev` 在vps存在ipv6地址的情况下才会使用 `["[::0]","0.0.0.0"]` ，`ss-rust` 只会是 `0.0.0.0` 。

> 另外建议脚本安装cloak插件的时候，设置redirect IP可以设置为域名，不是IP，这样即使那个要伪装的网站的IP变了也不影响。

这条建议我再看看（不一定会改），谢谢！

**Comment by windstander** [comment]
> 
> 
> 代码中只判断了 `ss-libev` 在vps存在ipv6地址的情况下才会使用 `["[::0]","0.0.0.0"]` ，`ss-rust` 只会是 `0.0.0.0` 。
> 
> > 另外建议脚本安装cloak插件的时候，设置redirect IP可以设置为域名，不是IP，这样即使那个要伪装的网站的IP变了也不影响。
> 
> 这条建议我再看看（不一定会改），谢谢！

那么ss rust的配置文件被设置为["[::0]","0.0.0.0"]是谁干的？如果不是脚本做的，那就是vps自己干的？我不是专业人士，搞不懂。

**Comment by loyess** [comment]
你新开一个vps，再安装一遍 ss-rust + cloak ，`cat /etc/shadowsocks/config.json` 查看配置，看看是否还是 ["[::0]","0.0.0.0"] 。

**Comment by windstander** [comment]
> 
> 
> 你新开一个vps，再安装一遍 ss-rust + cloak ，`cat /etc/shadowsocks/config.json` 查看配置，看看是否还是 ["[::0]","0.0.0.0"] 。

Lightsail和Linode不会，我就是这么对比出来的。

**Comment by windstander** [comment]
你这脚本真好，更新服务器端也很方便。

Cloak 2.4 增加了服务器端CDN模式的选项，你看是否需要更新：
https://github.com/cbeuw/Cloak/releases/tag/v2.4.0
https://github.com/cbeuw/Cloak/wiki/CDN-mode

**Comment by loyess** [comment]
CDN模式一直就有，并不是新功能。它支持的CDN是CloudFront，不是Cloudflare，个人觉得实用性不强，所以脚本没有包含。

**Comment by windstander** [comment]
> 
> 
> CDN模式一直就有，并不是新功能。它支持的CDN是CloudFront，不是Cloudflare，个人觉得实用性不强，所以脚本没有包含。

哦，是的，感谢你的脚本。

**Comment by windstander** [comment]
About还是写的Shadowsocks-libev with plugins，可以改一下了。

**Comment by IrineSistiana** [comment]
![image](https://user-images.githubusercontent.com/49315432/110211103-00674f80-7ed0-11eb-9789-2daac5fdf44f.png)

遇到一样的问题 +1
