### ISSUE TITLE
希望可以添加gost-plugin

### ISSUE THREAD

**Issue by maskedeken** [loyess/Shell#64]
[https://github.com/maskedeken/gost-plugin](https://github.com/maskedeken/gost-plugin) 

不仅可以作为mos-tls-tunnel的替代，还支持xtls

**Comment by loyess** [comment]
之前打算加入的，但发现好像没有Android端，就没弄了。

**Comment by maskedeken** [comment]
> 
> 
> 之前打算加入的，但发现好像没有Android端，就没弄了。

刚写了个预览版[https://github.com/maskedeken/gost-plugin-android](https://github.com/maskedeken/gost-plugin-android)

**Comment by loyess** [comment]
抱歉，回复的有点迟。

现在gost-plugin已经添加了，你的发布页面的二进制版本，http2 quic 还不支持，可能需要更新下！

**Comment by maskedeken** [comment]
> 
> 
> 抱歉，回复的有点迟。
> 
> 现在gost-plugin已经添加了，你的发布页面的二进制版本，http2 quic 还不支持，可能需要更新下！

已添加最新的release

**Comment by loyess** [comment]
@maskedeken  https://github.com/maskedeken/gost-plugin-android

冒昧问一下，此项目有开源的打算吗？

**Comment by maskedeken** [comment]
> 
> 
> @maskedeken https://github.com/maskedeken/gost-plugin-android
> 
> 冒昧问一下，此项目有开源的打算吗？

很抱歉，暂时还没有开源的打算
