### ISSUE TITLE
teddysun：xray-plugin

### ISSUE THREAD

**Issue by kfen** [loyess/Shell#65]
算是提需求把，啥时候抽空看看可以考虑加上，现在Xray-core慢慢开始流行起来了，而且解决了V很多的历史遗留问题。

https://github.com/teddysun/xray-plugin

**Comment by loyess** [comment]
脚本在传输模式上已经有很多重复的部分了，这个加进来也是一样的代理套路，没太大的必要，v2ray-plugin就很不错了，之后再看吧。

**Comment by loyess** [comment]
把gost-plugin加进来，是因为它有xtls可以用，xray-plugin好像没啥我想要用的。

**Comment by kfen** [comment]
> 脚本中部分插件在传输模式上已经有很多重复的部分了，这个加进来也是一样的代理套路，没太大的必要，v2ray-plugin就很不错了，之后再看吧。

代理套路基本是差不多，但是同线路的情况，貌似Xray-core效率上是优于v2ray-core，架构也进行了简化，而且也支持在op系统上使用了，还是比较方便。

**Comment by kfen** [comment]
https://github.com/teddysun/xray-plugin-android

秋水大佬安卓版也进行了跟进，用于 shadowsocks-libev，shadowsocks-rust 或 go-shadowsocks2，用法等同于 v2ray-plugin。

**Comment by windstander** [comment]
> 
> 
> 把gost-plugin加进来，是因为它有xtls可以用，xray-plugin好像没啥我想要用的。

这个插件有什么用，也是混淆？
