### ISSUE TITLE
似乎最新的脚本中xray-plugin没有Http方式混淆了

### ISSUE THREAD

**Issue by ricksuzade-maker** [loyess/Shell#67]
不知道是不是这样，特别咨询一下

**Comment by loyess** [comment]
ws 选项实际上是：Shadowsocks over websocket (HTTP)

ws 选项如果开启 web 就变成了：Shadowsocks over websocket (HTTPS)

wss 选项也是 Shadowsocks over websocket (HTTPS)，只是没有web可以开启。

**Comment by kfen** [comment]
这个问题我也注意到了，我看源码里是有配置的，我还以为哪里出问题了。
应该是下面这段：
`get_input_mirror_site(){
    while true
    do
        echo
        echo -e "${Tip} 该站点建议满足(位于海外、支持HTTPS协议、会用来传输大流量... )的条件，默认站点，随意找的，不建议使用"
        read -e -p "请输入你需要镜像到的站点(默认：https://www.bing.com)：" mirror_site
        [ -z "${mirror_site}" ] && mirror_site="https://www.bing.com"
        if [ -z "$(echo $mirror_site | grep -E ${HTTPS_DOMAIN_RE})" ]; then
            echo
            echo -e "${Error} 请输入以${Red} https:// ${suffix}开头，以${Red} 域名 ${suffix}结尾的URL."
            echo
            continue
        fi

        echo
        echo -e "${Red}  mirror_site = ${mirror_site}${suffix}"
        echo
        break
    done`

**Comment by loyess** [comment]
你的意思是，没有自定义host参数的选项吗？

**Comment by kfen** [comment]
> @kfen
> 你的意思是，没有自定义host参数的选项吗？

@loyess  
其实这样的，因为之前我用V2的插件，在配置完自己域名的解析之后，脚本会再要求配置一个https网站的，是用于大流量混淆之用，xray插件脚本是没有的，但是我看源码里又有，所以我也不知道到底哪里出了问题。

**Comment by loyess** [comment]
有这个选项，你要用ws 并 启用web服务器伪装，才有这个选项。

**Comment by kfen** [comment]
> 有这个选项，你要用ws 并 启用web服务器伪装，才有这个选项。

了解了，我选择了wss了，感谢作者耐心解答~

**Comment by loyess** [comment]
wss 是v2ray-plugin的 2选项，quic 就是 3 选项。

**Comment by kfen** [comment]
> wss 是v2ray-plugin的 2选项，quic 就是 3 选项。

@loyess   完美，搞定。
```
[信息] Shadowsocks-libev (pid 8119) is already running.
[信息] Xray-plugin (pid 8125) is already running.
[信息] Caddy (pid 8143) is already running.
```

**Comment by l3617** [comment]
> ws选项实际上是：在websocket（HTTP）上的影子
> 
> ws选项如果开启web就变成了：shadowsocks over websocket（HTTPS）
> 
> wss选项也是websocket（HTTPS）上的Shadowsocks，只是没有web可以开启。

那为何我的SS-rust xray-plugin＋ws没有https安装成功却不能启动，用v2ray-plugin插件却可以呢

**Comment by loyess** [comment]
@l3617  

检查 ssserver 和 xray-plugin 二进制文件是否能正常被执行。

如果执行 ssserver -h 终端上输出： Illegal instruction

请参考：#66

事实上，我有简单的测试过各个模式组合，都能正常启动并正常被客户端连接，你如果仍不能启动，请提供更多信息。

你也可以执行： ` cat /var/log/shadowsocks-rust.log` 命令， 查看日志信息。（如果日志文件存在的话）
