### ISSUE TITLE
9. gost-plugin下的xtls咨询

### ISSUE THREAD

**Issue by Jacky-Bruse** [loyess/Shell#68]
请教大佬， gost-plugin下面的xtls就是xray的那个xtls吗？

**Comment by loyess** [comment]
是的，就是那个xtls。

**Comment by Jacky-Bruse** [comment]
> 是的，就是那个xtls。
> 
> 项目链接参考：#64

这个安卓怎么用啊？我用xray-plugin没有这个选项啊，gost-plugin找不到安卓端的apk

**Comment by l3617** [comment]
> 是的，就是那个xtls。
> 
> 项目链接参考：[＃64](https://github.com/loyess/Shell/issues/64)

现在很多国内鸡封掉国外的443 80端口了，可是好像脚本不能用其他端口，希望添加此功能
