### ISSUE TITLE
部署ss+cloak无法链接

### ISSUE THREAD

**Issue by Hogeexxl** [loyess/Shell#7]
用脚本部署ss+cloak，使用默认的ip和域名（bing）
cloak和ss使用最新版

**Comment by loyess** [comment]
防火墙将端口放行了没有？

**Comment by Hogeexxl** [comment]
> 防火墙将端口放行了没有？
GCP，端口全开，DB 9系统，使用root账户
配置完成后直接用url导入ss，到这一步无任何报错提示
通过/etc/cloak/ckserver.json 希望查看配置，结果显示 Permission denied

**Comment by loyess** [comment]
等我用Debian9尝试安装后，给你答复

**Comment by loyess** [comment]
经过安装测试，Debian9安装过程没问题，安装完毕后，导入ss链接，连接正常！在手机端测试

**Comment by loyess** [comment]
你用ps命令查看ss和Cloak有没有运行成功

**Comment by Hogeexxl** [comment]
在无法联通的情况下，我进行了如下操作：
1. systemctl status cloak 查看cloak状态，发现没有成功启动
显示：http://img.hogee.fun/20190930174117.png
2.systemctl enable cloak 尝试启动cloak
http://img.hogee.fun/20190930174158.png
3. 再次查看 cloak状态，发现启动成功
http://img.hogee.fun/20190930174248.png
但最后依然无法翻墙

**Comment by loyess** [comment]
你应该使用这样的命令去启动
`/etc/init.d/cloak start`

**Comment by loyess** [comment]
你贴的图片链接，都不能显示
