### ISSUE TITLE
能否适配ax1800/3600系列

### ISSUE THREAD

**Issue by xumng** [loyess/Shell#71]
能否适配ax1800/3600系列，目前shellclash不支持xtls及vless，shell ssr+是否可以？

**Comment by loyess** [comment]
或许，你应该去 shellclash 项目提交 issue ，或者换个路由器固件，至于什么固件支持xtls及vless系列的ss插件，可能需要你自己尝试了。本项目脚本只提供SS和其插件在linux-amd64 处理器架构的服务器端的安装。
