### ISSUE TITLE
能否在安装时增加设置是否开启ipv6 first

### ISSUE THREAD

**Issue by ChellyL** [loyess/Shell#76]
有些vps带ipv6，ss设置ipv6_first为true可以优先走ipv6，方便跳google的验证
安装后再手动加有点麻烦

**Comment by loyess** [comment]
本来可以检测的，后来发现容易导致无法连接，就去掉了。这几种语言写的ss，启用ipv6的设置还有点不一样。

**Comment by loyess** [comment]
哦，刚看了下，好像有检测ipv6的，除了搭配插件4,6,7是强制ipv4，其他的都可以ipv6，就是配置文件里没有 ipv6_first 。
