### ISSUE TITLE
shadowsocks-rust 搭建后无法使用

### ISSUE THREAD

**Issue by zhao123gg** [loyess/Shell#79]
shadowsocks-rust 搭建后无法使用

**Comment by zhao123gg** [comment]
shadowsocks-libev 搭建可以使用

**Comment by zhao123gg** [comment]
> 可能端口没有打开，或者不是 amd64 的Linux，自行排查吧，确认ss-rust是可以用的。

使用 centos7 与debian 都是第一次全通，第二次以后全红

**Comment by loyess** [comment]
@jeffshead  
> ==> /var/log/shadowsocks-rust.log <== /usr/local/bin/ssserver: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/bin/ssserver)

ss-rust 日志文件有报错，你的系统 glibc 库版本过低，升级它可以解决。

使用以下命令查看该库是否包含 GLIBC_2.18
`strings /usr/lib64/libc.so.6 | grep ^GLIBC_`
或
`strings /lib64/libc.so.6 | grep ^GLIBC_`

**Comment by jeffshead** [comment]
# strings /usr/lib64/libc.so.6 | grep ^GLIBC_
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_PRIVATE
GLIBC_2.8
GLIBC_2.5
GLIBC_2.9
GLIBC_2.7
GLIBC_2.6
GLIBC_2.11
GLIBC_2.16
GLIBC_2.10
GLIBC_2.17
GLIBC_2.13
GLIBC_2.2.6

**Comment by root9000** [comment]
先安装一遍纯shadowsocks-libev不带任何插件，然后卸载再安装shadowsocks-rust即可，亲测可行

**Comment by zhao123gg** [comment]
> 先安装一遍纯shadowsocks-libev不带任何插件，然后卸载再安装shadowsocks-rust即可，亲测可行

你用的啥系统几版本😂

**Comment by root9000** [comment]
> > 先安装一遍纯shadowsocks-libev不带任何插件，然后卸载再安装shadowsocks-rust即可，亲测可行
> 
> 你用的啥系统几版本😂

干净的 Debian 11

**Comment by luodaoyi** [comment]
你这个问题跟我之前的是一样的
https://github.com/loyess/Shell/issues/98

现在已经换了musl的静态链接库版本了 应该可以用了的
