### ISSUE TITLE
能不能脚本中搞个多功能菜单

### ISSUE THREAD

**Issue by xidcn** [loyess/Shell#8]
比如说安装之后 再次启动脚本 在BBR 和安装和卸载 之外有重启 什么的脚本菜单
比如这样：

主菜单
  Shadowsocks-libev一键管理脚本[v1.0.0]

  1. BBR
  2.安装
  3.卸载
  4.启动SS
  5.重启SS
  6.重启caddy
  7.查看状态
  8.更新升级
 当前状态：已安装并已启动

请输入数字[1-8]：

然后ws-tls-web 哪里默认是反代，如果自己做网站该怎么配置，如果加个选项配置自己网站来伪装，我们可以有更好的选择 ，作者的脚本对于我这种小白很是受用，这几天想不反代，自己做网站，又不会配置 搞挂好多次梯子 对于我来说比较头疼. 最后希望脚本越来越好，越来越完善

**Comment by loyess** [comment]
你说的多功能菜单的功能，都有的，直接用命令就行了，这个就没必要弄了！至于你说的，加入建立自己网站的设置，也挺简单的，改一下caddy配置就可以了，我考虑考虑！暂时没空去弄。

**Comment by loyess** [comment]
如果你有现成的网站，而且不在同一个服务器，也可以直接反代到你自己的网站！

**Comment by loyess** [comment]
> ./ss-plugins.sh install         # 安装
> ./ss-plugins.sh uninstall    # 卸载
> ./ss-plugins.sh start           # 启动
> ./ss-plugins.sh stop           # 停止
> ./ss-plugins.sh restart       # 重启
> ./ss-plugins.sh status        # 状态
> ./ss-plugins.sh show          # 终端配置展示
> ./ss-plugins.sh uid              # Cloak用户管理
> ./ss-plugins.sh link             # Cloak链接生成
> ./ss-plugins.sh scan           # SS链接生成二维码
> ./ss-plugins.sh help            # 打印帮助信息

> /etc/init.d/shadowsocks-libev start|stop|restart|status

> /etc/init.d/kcptun start|stop|restart|status

> /etc/init.d/caddy start|stop|restart|status

> /etc/init.d/cloak start|stop|restart|status

**Comment by xidcn** [comment]
> 如果你有现成的网站，而且不在同一个服务器，也可以直接反代到你自己的网站！

在同一服务器

**Comment by loyess** [comment]
那就修改caddy的配置文件吧
