### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by quanljh** [loyess/Shell#82]
This issue was introduced by b0b1a16fa4c33acb61949b6103bb160963918a0b, 
The root cause should be the protocol was set to TLSv1.3.
I reverted code changes and tested it again, working now.
![Snipaste_2021-12-09_19-42-23](https://user-images.githubusercontent.com/38105306/145392084-8113592f-8506-43b2-92bf-40cb3de089d6.png)

**Comment by loyess** [comment]
Please use the client in the link below：
[v2ray-plugin (teddysun)](https://github.com/teddysun/v2ray-plugin)
[v2ray-plugin-android (teddysun)](https://github.com/teddysun/v2ray-plugin-android)

**Comment by quanljh** [comment]
I was using the teddysun's version and get that error.

**Comment by loyess** [comment]
证书的算法，从默认的RSA更改为了ECC，证书所在目录也从原来的 /root/.acme.sh/${domain} 变成了 /root/.acme.sh/${domain}_ecc ，如果你用的是原来的的域名，去安装，申请证书那一步可能会出现问题。

你可以 使用 acme.sh 指令删除原来申请的证书：
```
acme.sh --remove --domain your-domain.com --ecc
```
然后，手动删除 /root/.acme.sh/${domain}_ecc 目录，里面是你相关域名的证书文件。

之后，执行 ./ss-plugin.sh 正常安装，就可以了。

你也可以用，其它域名，或者，子域名尝试。

**Comment by loyess** [comment]
删除原来的RSA证书，应该不用加 --ecc

**Comment by quanljh** [comment]
It doesn't work for me... I removed the original cert and used ecc to test, same error.

**Comment by quanljh** [comment]
Closing this, cause my system is CentOS 7, by default, the openssl version doesn't support TLS1.3.

**Comment by quanljh** [comment]
Instead of setting TLS1.3 only in niginx config, suggest checking if the openssl version support TLS1.3 first (above or equal 1.1.1) and then set config accordingly.
