### ISSUE TITLE
Mux bug

### ISSUE THREAD

**Issue by darkrenz** [loyess/Shell#90]
![1642857814048](https://user-images.githubusercontent.com/30442976/150640335-4fdc3743-8d54-48c8-9927-1b6c075a533e.png)

Disable mux option not working.. 
It was tested on both shadowsocks versions
Like Shadowsocks Rust and Shadowsocks Libev but still the same.

如果你不明白我的话，请在谷歌翻译上翻译 !

**Comment by darkrenz** [comment]
I was using Vultr Deb 9

**Comment by loyess** [comment]
输入 y 不就禁用了么。

**Comment by darkrenz** [comment]
> 输入 y 不就禁用了么。

Copy 😉
