### ISSUE TITLE
安装shadowsocks-rust+simple-obfs(http)的组合之后端口tcping不通，无法连接

### ISSUE THREAD

**Issue by qqyc** [loyess/Shell#96]
dd过的新系统 debian11
安装的为shadowsocks-rust aes-256-gcm+simple-obfs（http）
没安装过防火墙 只有iptables禁用过25端口

**Comment by loyess** [comment]
检查vps服务商 端口设置，或者 打开全部端口试试。

**Comment by qqyc** [comment]
默认就是打开全部端口的，因为主机是独立ip的vps 测试过几台dd成debian11之后的新vps都是一样的

**Comment by loyess** [comment]
各个服务商对端口开放都有细微的差别，代码中只随意处理了下，有的适用有的不适用。
实在不行就开放全部端口吧：
```
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -F
```

**Comment by loyess** [comment]
应该说 Debian Ubuntu 端口开放，在代码中基本没处理，代码中是这么写的：
```
if [ "$(command -v ufw)" ] && [ -n "$(ufw status | head -n 1 | grep 'Status: active')" ]; then
    ufw allow ${PORT}/tcp
    ufw allow ${PORT}/udp
    ufw reload
else
    _echo -w "ufw没有运行或没有安装，请自行排查问题后，手动启用端口: ${PORT}."
fi
```
只有 安装了 ufw 并且 ufw在运行中，才会执行打开端口的命令，否者提示手动处理。

没 iptables 什么事。

**Comment by loyess** [comment]
备份：[Debian/Ubuntu/CentOS 的防火墙差异](https://lishuma.com/archives/3634)

**Comment by qqyc** [comment]
> 备份：[Debian/Ubuntu/CentOS 的防火墙差异](https://lishuma.com/archives/3634)

刚刚测试了已复现问题：
ss-rust 256gcm+simple-obfs(http)的组合不通，ss-libev 256gcm+simple-obfs(http)的组合通
ss-rust 256gcm通，ss-libev 256gcm通
是不是脚本的问题？

**Comment by loyess** [comment]
建议看看进程有没有在后台运行，也可以看看日志记录什么状态，我测试了脚本没问题，你所说的都是可以连通的，大概率还是端口问题。

**Comment by qqyc** [comment]
> 日志记录什么状态

进程是在跑的 日志在兼听相应端口后就没有其他的东西了，系统重装了debian11没有安装任何其他额外的东西，vps是斯巴达的

**Comment by qqyc** [comment]
> 

只有shadowsocks-rust+simple-obfs(http)会出问题

**Comment by loyess** [comment]
不清楚，你这种是什么状况，我dd了一个 Debian 11 ，安装 shadowsocks-rust+simple-obfs(http) ，连接正常。大概率还是端口问题。

**Comment by loyess** [comment]
你可以试试把配置文件中 :: 换成 0.0.0.0 看是否能够连通。

**Comment by qqyc** [comment]
> 你可以试试把配置文件中 :: 换成 0.0.0.0 看是否能够连通。

还真是这个问题！😂
